version: '3'

services:
  app:
    build: .
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=secret
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
    volumes:
      - ./mytemplate:/opt/jboss/keycloak/themes/mytemplate
    ports:
      - 8080:8080
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    container_name: keycloak_mysql
    tty: true
    ports:
      - 3310:3306
    volumes:
      - .docker/data/.mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=secret




